apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebapi
  labels:
    app: samplewebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplewebapi
  template:
    metadata:
      labels:
        app: samplewebapi
    spec:
      containers:
      - name: samplewebapi
        image: helshabini/samplewebapi:latest
        ports:
        - containerPort: 80